### ISSUE TITLE
on Scala 2.11, version 1.1.2 may run afoul of sbt classpath issue

### ISSUE THREAD

**Issue by Philippus** [scala/scala-parser-combinators#197] opened 2019-04-06 07:31 UTC
https://github.com/Philippus/bump/pull/8 fails with the following exception in scala 2.11:

```
SemVer.nextStable removes pre-release information if available: Exception raised on property evaluation.
[info] > Exception: java.lang.AbstractMethodError: nl.gn0s1s.bump.SemVerParser$.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar()Lscala/util/DynamicVariable;
```
Looks like https://github.com/scala/scala-parser-combinators/pull/108 after testing locally.

Scala 2.12 and 2.13.0-RC1 are ok.

**Comment by SethTisue** [comment] 2019-04-06 07:32
I guess the next step is to try to find a standalone reproducer, to understand the nature of the problem?

**Comment by SethTisue** [comment] 2019-04-06 07:38
I don't think there's any huge rush here, in the short term if a project has trouble it can always add 1.1.1 or 1.1.2 to the classpath depending on whether they're on 2.13 or not, there are scenarios in which that wouldn't be okay, but I suspect such scenarios would be very rare, especially if the community build has never complained

regardless, I'll try to isolate the problem this morning

**Comment by SethTisue** [comment] 2019-04-06 08:09
I think the root cause must be that Scala 2.11 compiler itself has a dependency on scala-parser-combinators. that dependency was removed in 2.12.

**Comment by SethTisue** [comment] 2019-04-06 08:11
the problem goes away if you `set fork in Test := true`, because then the compiler and its dependencies aren't on the classpath

**Comment by SethTisue** [comment] 2019-04-06 08:15
we went through this before with scala-xml at https://github.com/scala/scala-xml/issues/195

**Comment by SethTisue** [comment] 2019-04-06 08:18
@eed3si9n why is this still happening even after https://github.com/sbt/zinc/pull/505 ? the bump repo is on sbt 1.2.8, which includes the fix

**Comment by SethTisue** [comment] 2019-04-06 08:23
the Shapeless repo only uses scala-parser-combinators in some example code, so this won't flow downstream to Shapeless users

**Comment by SethTisue** [comment] 2019-04-06 08:37
seems like we should back-publish 1.1.1 for 2.13.0-RC1 so people can avoid this issue that way

**Comment by xerial** [comment] 2019-04-06 19:53
I hit this issue and switching 1.1.1 or 1.1.2 or using `fork in True` can be tricky.

**Comment by SethTisue** [comment] 2019-04-06 20:18
> I hit this issue and switching 1.1.1 or 1.1.2 or using fork in True can be tricky.

Yeah. Perhaps people landing on this ticket would like to leave links with sample diffs from their projects, to help others>

Also, this is probably obvious once you've understood the issue, but it's probably worth stating explicitly:

Without one of those fixes, your repo isn't testing what it's supposed to be testing. And that was true even before we built and released 1.1.2.

**Comment by xerial** [comment] 2019-04-07 04:45
@SethTisue That's true. 

Although it might have some overhead, adding `fork in Test := True` is most reliable to isolate libraries used in sbt and target applications.

**Comment by eed3si9n** [comment] 2019-04-07 18:13
@SethTisue It's an sbt bug.

So basically sbt/zinc#505 fixed the bug for `run`

```diff
   def makeLoader(classpath: Seq[File], instance: ScalaInstance): ClassLoader =
-    filterByClasspath(classpath, makeLoader(classpath, instance.loader, instance))
+    filterByClasspath(classpath, makeLoader(classpath, instance.loaderLibraryOnly, instance))
```

 but didn't for `test` it seems.

https://github.com/sbt/sbt/blob/v1.2.8/testing/src/main/scala/sbt/TestFramework.scala#L258

```scala
    val dual = new DualLoader(
      scalaInstance.loader,
```

I opened https://github.com/sbt/sbt/issues/4609.

**Comment by SethTisue** [comment] 2019-04-07 18:54
(closing the ticket since the bug isn't in this repo. still good we have this ticket to help searchers)

**Closed** 2019-04-07 18:53 UTC

**Comment by OlegYch** [comment] 2020-02-22 14:29
so, is 1.1.2 compatible with 1.0.4 or not? is 1.1.1 compatible with 1.0.4?

**Comment by OlegYch** [comment] 2020-02-22 15:19
ok, i did some tests and see that while technically a lib compiled against 1.0.4  (play_2.11-2.5.18) still references a method which is no longer available it seems to never be called

```
private DynamicVariable scala$util$parsing$combinator$Parsers$$lastNoSuccessVar$lzycompute() { synchronized (this) { if (!this.bitmap$0) { this.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar = Parsers.class.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar(this); this.bitmap$0 = true; } return this.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar; }  } 
public DynamicVariable<Option<Parsers.NoSuccess>> scala$util$parsing$combinator$Parsers$$lastNoSuccessVar() { return this.bitmap$0 ? this.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar : scala$util$parsing$combinator$Parsers$$lastNoSuccessVar$lzycompute(); } 
```

**Comment by OlegYch** [comment] 2020-02-23 00:17
then again, i'm not sure why would not-forking would cause a problem...

**Comment by SethTisue** [comment] 2020-02-23 00:19
>  i'm not sure why would not-forking cause a problem.

because https://github.com/scala/scala-parser-combinators/issues/197#issuecomment-480484934

**Comment by OlegYch** [comment] 2020-02-23 00:24
@SethTisue so if i have a dependency like scala-compiler had i will have a problem too? i have a lib compiled again 1.0.4, should i expect it to fail running against 1.1.2?

**Comment by SethTisue** [comment] 2020-02-23 00:53
I'm sorry, I don't know I haven't followed the status of the different branches that closely, where and when MiMa was enabled, and so on.
