### ISSUE TITLE
scalajs library for 1.0.6 is empty

### ISSUE THREAD

**Issue by justjoheinz** [scala/scala-parser-combinators#126] opened 2017-09-01 11:51 UTC
The jar file for the scalajs version 1.0.6 is empty, aka does not contain the code, just a meta-inf and js properties file.

Version 1.0.5 is working fine.

**Comment by xuwei-k** [comment] 2017-09-01 11:59
https://github.com/scala/scala-parser-combinators/issues/119

**Comment by SethTisue** [comment] 2017-10-12 21:43
yup, duplicate of #119. there is not yet a 1.0.7 release with the fix

**Closed by SethTisue** 2017-10-12 21:43 UTC
