### ISSUE TITLE
Link for ScalaJS broken

### ISSUE THREAD

**Issue by MikaelMayer** [scala/scala-parser-combinators#122] opened 2017-07-21 12:35 UTC
The [Readme](https://github.com/scala/scala-parser-combinators) file says it supports scala-js using the following dependency:

    libraryDependencies += "org.scala-lang.modules" %%% "scala-parser-combinators" % "1.0.6"

However, even in a simple project e.g. [Workbench Example App](https://github.com/lihaoyi/workbench-example-app), adding the line above in the build.sbt file and an import statement like:

    import scala.util.parsing.combinator._

triggers the error:

> object parsing is not a member of package util

The solution for me was to use another link provided by [this stackoverflow answer](https://stackoverflow.com/a/22989055/1287856)

    libraryDependencies += "org.scala-js" %%% "scala-parser-combinators" % "1.0.2"

but in this case, 1.0.6 is not supported. Any idea why?

**Comment by SethTisue** [comment] 2017-07-21 12:38
Duplicate of #119; will be fixed in 1.0.7

**Closed by SethTisue** 2017-07-21 12:38 UTC
